package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private int id;
     private Curso curso;
     private Matricula matricula;
     private Boolean estado;
     private Date fecha;

    public Asistencia() {
    }

	
    public Asistencia(int id, Curso curso, Matricula matricula) {
        this.id = id;
        this.curso = curso;
        this.matricula = matricula;
    }
    public Asistencia(int id, Curso curso, Matricula matricula, Boolean estado, Date fecha) {
       this.id = id;
       this.curso = curso;
       this.matricula = matricula;
       this.estado = estado;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}


