package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0



/**
 * Citacion generated by hbm2java
 */
public class Citacion  implements java.io.Serializable {


     private int id;
     private Evidencia evidencia;
     private Curso curso;
     private Empleado empleado;
     private Estudiante estudiante;
     private String descripcion;

    public Citacion() {
    }

    public Citacion(int id, Evidencia evidencia, Curso curso, Empleado empleado, Estudiante estudiante, String descripcion) {
       this.id = id;
       this.evidencia = evidencia;
       this.curso = curso;
       this.empleado = empleado;
       this.estudiante = estudiante;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Evidencia getEvidencia() {
        return this.evidencia;
    }
    
    public void setEvidencia(Evidencia evidencia) {
        this.evidencia = evidencia;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


