package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable{


     private int id;
     private String anioegb;
     private String paralelo;
     private String periodo;
     private String jornada;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);
     private Set<Materia> materias = new HashSet<Materia>(0);
     private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);
     private Set<Citacion> citacions = new HashSet<Citacion>(0);

    public Curso() {
    }

	
    public Curso(int id, String anioegb, String paralelo, String periodo, String jornada) {
        this.id = id;
        this.anioegb = anioegb;
        this.paralelo = paralelo;
        this.periodo = periodo;
        this.jornada = jornada;
    }
    public Curso(int id, String anioegb, String paralelo, String periodo, String jornada, Set<Matricula> matriculas, Set<Materia> materias, Set<Asistencia> asistencias, Set<Citacion> citacions) {
       this.id = id;
       this.anioegb = anioegb;
       this.paralelo = paralelo;
       this.periodo = periodo;
       this.jornada = jornada;
       this.matriculas = matriculas;
       this.materias = materias;
       this.asistencias = asistencias;
       this.citacions = citacions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAnioegb() {
        return this.anioegb;
    }
    
    public void setAnioegb(String anioegb) {
        this.anioegb = anioegb;
    }
    public String getParalelo() {
        return this.paralelo;
    }
    
    public void setParalelo(String paralelo) {
        this.paralelo = paralelo;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getJornada() {
        return this.jornada;
    }
    
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }
    public Set<Materia> getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }
    public Set<Asistencia> getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set<Asistencia> asistencias) {
        this.asistencias = asistencias;
    }
    public Set<Citacion> getCitacions() {
        return this.citacions;
    }
    
    public void setCitacions(Set<Citacion> citacions) {
        this.citacions = citacions;
    }
    @Override
    public String toString() {
        return String.format("%s Paralelo: %s", this.anioegb, this.paralelo);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Curso other = (Curso) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.anioegb == null) ? (other.anioegb != null) : !this.anioegb.equals(other.anioegb)) {
            return false;
        }
        return true;
    }



}


