package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int id;
     private String usuario;
     private String password;
     private String nombre;
     private String apellido;
     private Boolean estado;
     private Set<Materia> materias = new HashSet<Materia>(0);
     private Set<Citacion> citacions = new HashSet<Citacion>(0);
     private Set<Rolempleado> rolempleados = new HashSet<Rolempleado>(0);

    public Empleado() {
    }

	
    public Empleado(int id, String usuario, String password, String nombre, String apellido) {
        this.id = id;
        this.usuario = usuario;
        this.password = password;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Empleado(int id, String usuario, String password, String nombre, String apellido, Boolean estado, Set<Materia> materias, Set<Citacion> citacions, Set<Rolempleado> rolempleados) {
       this.id = id;
       this.usuario = usuario;
       this.password = password;
       this.nombre = nombre;
       this.apellido = apellido;
       this.estado = estado;
       this.materias = materias;
       this.citacions = citacions;
       this.rolempleados = rolempleados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<Materia> getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }
    public Set<Citacion> getCitacions() {
        return this.citacions;
    }
    
    public void setCitacions(Set<Citacion> citacions) {
        this.citacions = citacions;
    }
    public Set<Rolempleado> getRolempleados() {
        return this.rolempleados;
    }
    
    public void setRolempleados(Set<Rolempleado> rolempleados) {
        this.rolempleados = rolempleados;
    }




}


