package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private String direccion;
     private String representante;
     private String telefono;
     private Set<Citacion> citacions = new HashSet<Citacion>(0);
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public Estudiante() {
    }

	
    public Estudiante(int id, String nombre, String apellido, String direccion, String representante, String telefono) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.representante = representante;
        this.telefono = telefono;
    }
    public Estudiante(int id, String nombre, String apellido, String direccion, String representante, String telefono, Set<Citacion> citacions, Set<Matricula> matriculas) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.representante = representante;
       this.telefono = telefono;
       this.citacions = citacions;
       this.matriculas = matriculas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(String representante) {
        this.representante = representante;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Citacion> getCitacions() {
        return this.citacions;
    }
    
    public void setCitacions(Set<Citacion> citacions) {
        this.citacions = citacions;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }

    @Override
    public String toString() {
        return String.format("%s %s",apellido.toUpperCase(), nombre.toUpperCase());
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Estudiante other = (Estudiante) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

}


