package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Evidencia generated by hbm2java
 */
public class Evidencia  implements java.io.Serializable {


     private int id;
     private Parametro parametro;
     private String tipocitacion;
     private String rutarelativa;
     private Set<Citacion> citacions = new HashSet<Citacion>(0);

    public Evidencia() {
    }

	
    public Evidencia(int id, Parametro parametro, String tipocitacion) {
        this.id = id;
        this.parametro = parametro;
        this.tipocitacion = tipocitacion;
    }
    public Evidencia(int id, Parametro parametro, String tipocitacion, String rutarelativa, Set<Citacion> citacions) {
       this.id = id;
       this.parametro = parametro;
       this.tipocitacion = tipocitacion;
       this.rutarelativa = rutarelativa;
       this.citacions = citacions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Parametro getParametro() {
        return this.parametro;
    }
    
    public void setParametro(Parametro parametro) {
        this.parametro = parametro;
    }
    public String getTipocitacion() {
        return this.tipocitacion;
    }
    
    public void setTipocitacion(String tipocitacion) {
        this.tipocitacion = tipocitacion;
    }
    public String getRutarelativa() {
        return this.rutarelativa;
    }
    
    public void setRutarelativa(String rutarelativa) {
        this.rutarelativa = rutarelativa;
    }
    public Set<Citacion> getCitacions() {
        return this.citacions;
    }
    
    public void setCitacions(Set<Citacion> citacions) {
        this.citacions = citacions;
    }




}


