package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private int id;
     private Curso curso;
     private Empleado empleado;
     private Planificacion planificacion;
     private String nombre;
     private Set<Quimestre> quimestres = new HashSet<Quimestre>(0);

    public Materia() {
    }

	
    public Materia(int id, Curso curso, Empleado empleado, Planificacion planificacion, String nombre) {
        this.id = id;
        this.curso = curso;
        this.empleado = empleado;
        this.planificacion = planificacion;
        this.nombre = nombre;
    }
    public Materia(int id, Curso curso, Empleado empleado, Planificacion planificacion, String nombre, Set<Quimestre> quimestres) {
       this.id = id;
       this.curso = curso;
       this.empleado = empleado;
       this.planificacion = planificacion;
       this.nombre = nombre;
       this.quimestres = quimestres;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Planificacion getPlanificacion() {
        return this.planificacion;
    }
    
    public void setPlanificacion(Planificacion planificacion) {
        this.planificacion = planificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Quimestre> getQuimestres() {
        return this.quimestres;
    }
    
    public void setQuimestres(Set<Quimestre> quimestres) {
        this.quimestres = quimestres;
    }

    @Override
    public String toString() {
        return nombre;
    }




}


