package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private int id;
     private Planificacion planificacion;
     private String nombre;
     private String descripcion;
     private Set<Unidad> unidads = new HashSet<Unidad>(0);

    public Modulo() {
    }

	
    public Modulo(int id, Planificacion planificacion, String nombre, String descripcion) {
        this.id = id;
        this.planificacion = planificacion;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Modulo(int id, Planificacion planificacion, String nombre, String descripcion, Set<Unidad> unidads) {
       this.id = id;
       this.planificacion = planificacion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.unidads = unidads;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Planificacion getPlanificacion() {
        return this.planificacion;
    }
    
    public void setPlanificacion(Planificacion planificacion) {
        this.planificacion = planificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Unidad> getUnidads() {
        return this.unidads;
    }
    
    public void setUnidads(Set<Unidad> unidads) {
        this.unidads = unidads;
    }




}


