package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Parametro generated by hbm2java
 */
public class Parametro  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String valor;
     private Set<Evidencia> evidencias = new HashSet<Evidencia>(0);

    public Parametro() {
    }

	
    public Parametro(int id, String nombre, String valor) {
        this.id = id;
        this.nombre = nombre;
        this.valor = valor;
    }
    public Parametro(int id, String nombre, String valor, Set<Evidencia> evidencias) {
       this.id = id;
       this.nombre = nombre;
       this.valor = valor;
       this.evidencias = evidencias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Set<Evidencia> getEvidencias() {
        return this.evidencias;
    }
    
    public void setEvidencias(Set<Evidencia> evidencias) {
        this.evidencias = evidencias;
    }




}


