package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0



/**
 * Parcial generated by hbm2java
 */
public class Parcial  implements java.io.Serializable {


     private int id;
     private Quimestre quimestre;
     private int numero;
     private float calificacion;

    public Parcial() {
    }

    public Parcial(int id, Quimestre quimestre, int numero, float calificacion) {
       this.id = id;
       this.quimestre = quimestre;
       this.numero = numero;
       this.calificacion = calificacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Quimestre getQuimestre() {
        return this.quimestre;
    }
    
    public void setQuimestre(Quimestre quimestre) {
        this.quimestre = quimestre;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public float getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(float calificacion) {
        this.calificacion = calificacion;
    }




}


