package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Planificacion generated by hbm2java
 */
public class Planificacion  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set<Modulo> modulos = new HashSet<Modulo>(0);
     private Set<Materia> materias = new HashSet<Materia>(0);

    public Planificacion() {
    }

	
    public Planificacion(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public Planificacion(int id, String descripcion, Set<Modulo> modulos, Set<Materia> materias) {
       this.id = id;
       this.descripcion = descripcion;
       this.modulos = modulos;
       this.materias = materias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Modulo> getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set<Modulo> modulos) {
        this.modulos = modulos;
    }
    public Set<Materia> getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }




}


