package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Quimestre generated by hbm2java
 */
public class Quimestre  implements java.io.Serializable {


     private int id;
     private Matricula matricula;
     private Materia materia;
     private Integer numero;
     private Float examen;
     private Set<Parcial> parcials = new HashSet<Parcial>(0);

    public Quimestre() {
    }

	
    public Quimestre(int id, Matricula matricula, Materia materia) {
        this.id = id;
        this.matricula = matricula;
        this.materia = materia;
    }
    public Quimestre(int id, Matricula matricula, Materia materia, Integer numero, Float examen, Set<Parcial> parcials) {
       this.id = id;
       this.matricula = matricula;
       this.materia = materia;
       this.numero = numero;
       this.examen = examen;
       this.parcials = parcials;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Float getExamen() {
        return this.examen;
    }
    
    public void setExamen(Float examen) {
        this.examen = examen;
    }
    public Set<Parcial> getParcials() {
        return this.parcials;
    }
    
    public void setParcials(Set<Parcial> parcials) {
        this.parcials = parcials;
    }




}


