package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int id;
     private String tipo;
     private Set<Rolempleado> rolempleados = new HashSet<Rolempleado>(0);

    public Rol() {
    }

	
    public Rol(int id, String tipo) {
        this.id = id;
        this.tipo = tipo;
    }
    public Rol(int id, String tipo, Set<Rolempleado> rolempleados) {
       this.id = id;
       this.tipo = tipo;
       this.rolempleados = rolempleados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Rolempleado> getRolempleados() {
        return this.rolempleados;
    }
    
    public void setRolempleados(Set<Rolempleado> rolempleados) {
        this.rolempleados = rolempleados;
    }




}


