package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0



/**
 * Rolempleado generated by hbm2java
 */
public class Rolempleado  implements java.io.Serializable {


     private int id;
     private Rol rol;
     private Empleado empleado;

    public Rolempleado() {
    }

    public Rolempleado(int id, Rol rol, Empleado empleado) {
       this.id = id;
       this.rol = rol;
       this.empleado = empleado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }




}


