package com.sain.modelo;
// Generated 18/08/2014 04:31:06 PM by Hibernate Tools 3.6.0



/**
 * Unidad generated by hbm2java
 */
public class Unidad  implements java.io.Serializable {


     private int id;
     private Modulo modulo;
     private String nombre;
     private String descripcion;

    public Unidad() {
    }

    public Unidad(int id, Modulo modulo, String nombre, String descripcion) {
       this.id = id;
       this.modulo = modulo;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


